# Generated by Django 5.1.6 on 2025-02-09 20:28

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=100)),
                ('last_name', models.CharField(default='no last name', max_length=100)),
                ('dob', models.DateField(default='1900-01-01')),
                ('cronic_diseases', models.JSONField(blank=True, default=dict, null=True)),
                ('predispositions', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='wound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wound_location', models.CharField(default='no wound location', max_length=100)),
                ('wound_origin', models.CharField(default='no wound cause', max_length=100)),
                ('wound_origin_date', models.DateField(default=django.db.models.functions.datetime.Now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curametric_api.patient')),
            ],
            options={
                'verbose_name': 'Wound',
                'verbose_name_plural': 'Wounds',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='wound_care',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_date', models.DateField(default=django.db.models.functions.datetime.Now)),
                ('wound_heigh', models.FloatField(default=0)),
                ('wound_width', models.FloatField(default=0)),
                ('wound_depth', models.FloatField(default=0)),
                ('wound_necrotic_tissue', models.FloatField(default=0)),
                ('wound_sloughed_tissue', models.FloatField(default=0)),
                ('wound_granulation_tissue', models.FloatField(default=0)),
                ('wound_exudate_quantity', models.TextField(default='no exudate quantity')),
                ('wound_exudate_quality', models.TextField(default='no exudate quality')),
                ('wound_debridement', models.BooleanField(default=False)),
                ('wound_primary_dressing', models.TextField(default='no primary dressing')),
                ('wound_secondary_dressing', models.JSONField(blank=True, default=dict, null=True)),
                ('wound_next_care', models.DateField(default=django.db.models.functions.datetime.Now)),
                ('wound_care_notes', models.TextField(default='no notes')),
                ('wound_photo', models.ImageField(blank=True, null=True, upload_to='wound_photos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curametric_api.wound')),
            ],
            options={
                'verbose_name': 'Wound Care',
                'verbose_name_plural': 'Wound Cares',
                'ordering': ['created_at'],
            },
        ),
    ]
